
[props]
stem_len = 2
brightness = 0.5
range = 16.0
albedo = [0.66, 0.45, 0.24]

# base

[[cylinder]]
material = "diffuse"
reflect = 0.1
rough = 0.1
albedo = 'albedo'
height = 0.1
center_x = 0.0
pos_y = 0.0
center_z = 0.0
width = 0.8

[[cylinder]]
material = "diffuse"
reflect = 0.1
rough = 0.1
albedo = 'albedo'
height = 0.05
center_x = 0
pos_y = 0.1
center_z = 0
width = 0.6

[[cylinder]]
material = "diffuse"
reflect = 0.1
rough = 0.1
albedo = 'albedo'
height = 0.05
center_x = 0
pos_y = 0.15
center_z = 0
width = 0.4


# stem
[[cylinder]]
material = "diffuse"
texture = "wood"
reflect = 0.1
albedo = 'albedo'
height = 'stem_len'
center_x = 0
pos_y = 0.0
center_z = 0
width_bottom = 0.05
width_top = 0.2

[[cone]]
material = "diffuse"
reflect = 0.2
specular = 0.5
shininess = 50
albedo = 'albedo'
height = 0.3
width = 1
center_x = 0
pos_y = 'stem_len'
center_z = 0
rotate_x = 180
capped = false

[[light]]
color = [2, 1.5, 1]
pos = [0, 'stem_len + 0.5', 0]
brightness = 'brightness'
interactive = true
range = 'range'
radius = 0.5

