[[include]]
file = "server-rack.toml"
# migrated-center-at
at = [0.05, 1.3, 0.3]

[[include]]
file = "server.toml"
# migrated-center-at
at = [0.55, 1.95, 0.3]

[[include]]
file = "server.toml"
# migrated-center-at
at = [0.55, 1.25, 0.3]

[[include]]
file = "server.toml"
# migrated-center-at
at = [0.55, 0.55, 0.3]

[[include]]
file = "server-rack.toml"
# migrated-center-at
at = [1.05, 1.3, 0.3]

[[include]]
file = "server.toml"
# migrated-center-at
at = [1.55, 1.95, 0.3]

[[include]]
file = "server.toml"
# migrated-center-at
at = [1.55, 1.25, 0.3]

[[include]]
file = "server.toml"
# migrated-center-at
at = [1.55, 0.55, 0.3]


[[include]]
file = "server-rack.toml"
# migrated-center-at
at = [2.05, 1.3, 0.3]

[[include]]
file = "server.toml"
# migrated-center-at
at = [2.55, 1.95, 0.3]

[[include]]
file = "server.toml"
# migrated-center-at
at = [2.55, 1.25, 0.3]

[[include]]
file = "server.toml"
# migrated-center-at
at = [2.55, 0.55, 0.3]

[[include]]
file = "server-rack.toml"
# migrated-center-at
at = [3.05, 1.3, 0.3]

[[include]]
file = "server.toml"
# migrated-center-at
at = [3.55, 1.95, 0.3]

[[include]]
file = "server.toml"
# migrated-center-at
at = [3.55, 1.25, 0.3]

[[include]]
file = "server.toml"
# migrated-center-at
at = [3.55, 0.55, 0.3]

[[include]]
file = "server-rack.toml"
# migrated-center-at
at = [4.05, 1.3, 0.3]


