# Skyscrapers in the distance
[[box]]
rotate_y = 20
material = "diffuse"
reflect = 0.5
albedo = [0.01, 0.01, 0.01]
pos_x = -200.0
pos_y = 0.0
pos_z = 0.0
width = 30
height = 250
depth = 30


# Skyscrapers in the distance
[[box]]
rotate_y = 20
material = "diffuse"
reflect = 0.5
albedo = [0.01, 0.01, 0.01]
pos_x = -200.0
pos_y = 0.0
pos_z = 0.0
width = 50
height = 200
depth = 30

# Skyscrapers in the distance
[[box]]
rotate_y = -50
material = "diffuse"
reflect = 0.4
albedo = [0.01, 0.01, 0.01]
pos_x = -150.0
pos_y = 0.0
pos_z = -70.0
width = 50
height = 220
depth = 30

# Skyscrapers in the distance
[[cylinder]]
material = "diffuse"
reflect = 0.5
rotate_y = -10
albedo = [0.01, 0.01, 0.01]
pos_x = -130.0
pos_y = 0.0
pos_z = 50.0
width = 40
height = 180
depth = 30


# Skyscrapers in the distance
[[box]]
material = "diffuse"
reflect = 0.5
rotate_y = -10
albedo = [0.01, 0.01, 0.01]
pos_x = -120.0
pos_y = 0.0
pos_z = 70.0
width = 40
height = 180
depth = 30

[[box]]
material = "diffuse"
reflect = 0.6
albedo = [0.01, 0.01, 0.01]
pos_x = -120.0
pos_y = 180
pos_z = 70.0
width = 30
height = 30
depth = 30
rotate_y = -10


# Skyscrapers in the distance
[[box]]
material = "diffuse"
reflect = 0.5
rotate_y = -10
albedo = [0.01, 0.01, 0.01]
pos_x = -120.0
pos_y = 0.0
pos_z = -170.0
width = 40
height = 180
depth = 30

# Skyscrapers in the distance
[[box]]
material = "diffuse"
reflect = 0.5
rotate_y = -50
albedo = [0.01, 0.01, 0.01]
pos_x = -120.0
pos_y = 0.0
pos_z = 170.0
width = 40
height = 220
depth = 30

