[props]
width = 10
sheet_thickness = 0.07
beam_thickness = 1.5
albedo = [0.5,0.5,0.7]
rough = 0
reflect = 0

[const]
bolts = 'floor((width / 2) - 1)'

# top
[[box]]
pos_x = 0
pos_y = 0
pos_z = 0
reflect = 'reflect'
rough = 'rough'
width = 'width'
height = 'sheet_thickness'
depth = 'beam_thickness'
material = "diffuse"
texture = "cement"
albedo = 'albedo'

# middle
[[box]]
pos_x = 0
reflect = 'reflect'
texture = "cement"
rough = 'rough'
pos_y = '-beam_thickness'
pos_z = 'beam_thickness / 2'
width = 'width'
height = 'beam_thickness'
depth = 'sheet_thickness'
material = "diffuse"
albedo = 'albedo'

# bottom
[[box]]
pos_x = 0
reflect = 'reflect'
texture = "cement"
pos_y = '-beam_thickness'
rough = 'rough'
pos_z = 0
width = 'width'
height = 'sheet_thickness'
depth = 'beam_thickness'
material = "diffuse"
albedo = 'albedo'

# bolt caps

# for i in range(bolts)
[[sphere]]
center = ['(i + 1) * 2', '- beam_thickness / 2', 'beam_thickness / 2']
rough = 'rough'
material = "diffuse"
radius = 'sheet_thickness * 4'
reflect = 'reflect'
albedo = 'albedo'
# endfor
