[props]
case_albedo = [2.2, 2.2, 2]
screen_id = "workstation_display"
screen_brightness = 0.1
material = "diffuse"
albedo = [0.01, 0.01, 0.01]
reflect = 0.03
rough = 0.02
hint = "workstation"
use_range = 1.5
headline = "Headline"
paragraphs = []
font = "M42.ttf"
font_size_px = 14
font_color = [5.2, 5.2, 5.2]

[const]
ribs_albedo = 'vec3_scale(case_albedo, 0.3)'

# --- CRT monitor housing ---
[[box]]
material = "diffuse"
reflect = 0.005
albedo = 'case_albedo'
pos_x = -0.19
pos_y = 0.22
pos_z = -0.1
width = 0.38
height = 0.35
depth = 0.3

[[box]]
material = "diffuse"
reflect = 0.005
albedo = 'case_albedo'
pos_x = -0.15
pos_y = 0.27
pos_z = -0.2
width = 0.3
height = 0.25
depth = 0.1

# monitor screen
[[screen]]
id = 'screen_id'
material = 'material'
reflect = 'reflect'
rough = 'rough'
albedo = 'albedo'
pos_x = -0.15
pos_y = 0.28
pos_z = 0.205
width = 0.30
height = 0.25
depth = 0.001
hint = 'hint'
use_range = 1.5
headline = 'headline'
paragraphs = 'paragraphs'
font = 'font'
font_size_px = 'font_size_px'
font_color = 'font_color'

# monitor stand
[[sphere]]
material = "diffuse"
reflect = 0.05
albedo = 'case_albedo'
center = [0, 0.2, 0]
radius = 0.1

[[box]]
material = "diffuse"
reflect = 0.05
albedo = 'case_albedo'
pos_x = -0.15
pos_y = 0.13
pos_z = -0.15
width = 0.3
depth = 0.3
height = 0.02

# screen glow
[[light]]
pos = [0, 0.4, 0.4]
color = [1, 1, 6]
range = 1
brightness = 'screen_brightness'

# side ventilation ribs (monitor)
[[box]]
material = "diffuse"
albedo = 'ribs_albedo'
pos_x = -0.196
pos_y = 0.3
pos_z = -0.06
width = 0.006
height = 0.018
depth = 0.22

[[box]]
material = "diffuse"
albedo = 'ribs_albedo'
pos_x = -0.196
pos_y = 0.4
pos_z = -0.06
width = 0.006
height = 0.018
depth = 0.22

[[box]]
material = "diffuse"
albedo = 'ribs_albedo'
pos_x = -0.196
pos_y = 0.35
pos_z = -0.06
width = 0.006
height = 0.018
depth = 0.22

[[box]]
material = "diffuse"
albedo = 'ribs_albedo'
pos_x = 0.190
pos_y = 0.3
pos_z = -0.06
width = 0.006
height = 0.018
depth = 0.22

[[box]]
material = "diffuse"
albedo = 'ribs_albedo'
pos_x = 0.190
pos_y = 0.35
pos_z = -0.06
width = 0.006
height = 0.018
depth = 0.22

[[box]]
material = "diffuse"
albedo = 'ribs_albedo'
pos_x = 0.190
pos_y = 0.4
pos_z = -0.06
width = 0.006
height = 0.018
depth = 0.22
