
# floor
[[box]]
material = "diffuse"
texture = "marble"
albedo = [0.1, 0.1, 0.1]
pos_x = 0.0
pos_y = 0.0
pos_z = 0.0
width = 50.0
height = 0.2
depth = 50.0
reflect = 0.2
rough = 0.007

# ceiling
[[box]]
material = "diffuse"
texture = "cement"
albedo = [0.3, 0.3, 0.3]
pos_x = 0.0
pos_y = 8.0
pos_z = 0.0
width = 50.0
height = 0.2
depth = 50.0

# north wall
[[box]]
material = "diffuse"
albedo = [0.3, 0.3, 0.3]
pos_x = 0.0
pos_y = 0.0
pos_z = 0.0
width = 50.0
height = 8.0
depth = 0.2

# east wall
[[box]]
material = "diffuse"
albedo = [0.3, 0.3, 0.3]
pos_x = 0.0
pos_y = 0.0
pos_z = 0.0
width = 0.2
height = 8.0
depth = 50.0

# south wall
[[box]]
material = "diffuse"
albedo = [0.3, 0.3, 0.3]
pos_x = 0.0
pos_y = 0.0
pos_z = 25.0
width = 50.0
height = 8.0
depth = 0.2

# east wall
[[box]]
material = "diffuse"
albedo = [0.3, 0.3, 0.3]
pos_x = 49.8
pos_y = 0.0
pos_z = 0.0
width = 0.2
height = 8.0
depth = 50.8

# Door
[[box.hole]]
pos_x = 48
pos_y = 0
pos_z = 2
width = 3
height = 5.0
depth = 3

# cube
[[include]]
file = "objects/cube.toml"
at = [10.0, 1, 2.0]
rotate_y = 0.0

# server rack left of the cube
[[include]]
file = "objects/server-column.toml"
at = [3.0, 0.2, 8.0]
rotate_y = 30
instance = true

# server rack opposite the cube
[[include]]
file = "objects/server-column.toml"
at = [7.0, 0.2, 14.0]
rotate_y = -30
instance = true

# server racks right of the cube
[[include]]
file = "objects/server-column.toml"
at = [20.0, 0.2, 8.0]
rotate_y = 90
instance = true

[[include]]
file = "objects/server-column.toml"
at = [23.0, 0.2, 8.0]
rotate_y = 90
instance = true

[[include]]
file = "objects/server-column.toml"
at = [26.0, 0.2, 8.0]
rotate_y = 90
instance = true

[[include]]
file = "objects/server-column.toml"
at = [29.0, 0.2, 8.0]
rotate_y = 90
instance = true

# stairs to the cube
[[include]]
file = "../objects/staircase.toml"
at = [9.7, 0, 7.5]
rotate_y = 90
instance = true
params = { steps = 5, run = 0.3, rise = 0.2, width = 4, texture = "marble", reflect = 0.5 }

# Lamp 1
[[include]]
instance = true
file = "../objects/otto-wagner-sphere-lamp.toml"
at = [26.0, 8, 15.0]
params = { stem_len = 2.1, orb_radius = 0.5, brightness = 0.1, range = 10 }

# Lamp 2
[[include]]
instance = true
file = "../objects/otto-wagner-sphere-lamp.toml"
at = [30.0, 8, 15.0]
params = { stem_len = 2.1, orb_radius = 0.5, brightness = 0.1, range = 10 }

# Lamp 3
[[include]]
instance = true
file = "../objects/otto-wagner-sphere-lamp.toml"
at = [34.0, 8, 15.0]
params = { stem_len = 2.1, orb_radius = 0.5, brightness = 0.1, range = 10 }

# table to the right of the cube
[[include]]
file = "../objects/simple-table.toml"
at = [14.7, 0.2, 7.0]
rotate_y = -20
params = { width = 1.5, height = 0.9, texture = "wood" }
# glass bottle on the table
[[include]]
file = "../objects/glass-bottle.toml"
at = [14, 1.1, 7.3]
# ashtray on the table
[[include]]
file = "../objects/ashtray.toml"
at = [14.5, 1.1, 7.3]
rotate_y = -50



# table (desk) to the left of the cube
[[include]]
file = "../objects/simple-table.toml"
at = [7.0, 0.2, 10.0]
rotate_y = 20
params = { width = 2, height = 0.9, texture = "wood" }

# Laptop on the desk
[[include]]
file = "objects/laptop.toml"
at = [7.0, 1.1, 10.3]
rotate_y = 15

# glass bottle on the desk
[[include]]
file = "../objects/glass-bottle.toml"
at = [6.6, 1.1, 10.5]

# ashtray on the desk
[[include]]
file = "../objects/ashtray.toml"
at = [7.5, 1.1, 10.3]

