# floor
[[box]]
material = "diffuse"
texture = "marble"
albedo = [0.1, 0.1, 0.1]
pos_x = 0.0
pos_y = 0.0
pos_z = 0.0
width = 40.0
height = 0.2
depth = 20.0
reflect = 0.02
rough = 0.007

# ceiling
[[box]]
material = "diffuse"
texture = "cement"
albedo = [0.1, 0.1, 0.1]
pos_x = 0.0
pos_y = 8.0
pos_z = 0.0
width = 40.0
height = 0.2
depth = 20.0

# north wall
[[box]]
material = "diffuse"
texture = "cement"
albedo = [0.3, 0.3, 0.3]
pos_x = 0.0
pos_y = 0.0
pos_z = 0.0
width = 40.0
height = 8.0
depth = 0.2

# west wall (grid)
[[include]]
file = "../objects/grid.toml"
transform_origin = [0, 0, 0]
at = [0.0, 0.0, 20.0]
rotate_y = 90
props = { width = 20.0, height = 8.0, depth = 0.2, unit_size = 1, albedo = [1, 1, 1], material = "diffuse", texture = "cement"}

# glass wall (west)
[[box]]
material = "glass"
thin = true
ior = 1.1
rough = 0.01
transmit = 0.5
albedo = [1.2, 1.2, 1.2]
pos_x = 0
pos_y = 0
pos_z = 0
width = 0.01
height = 8.0
depth = 20

# west wall (solid top)
[[box]]
material = "diffuse"
texture = "cement"
albedo = [1,1,1]
pos_x = 0.0
pos_y = 4.2
pos_z = 0.0
width = 0.2
height = 4
depth = 20.0

# south wall
[[box]]
material = "diffuse"
texture = "cement"
albedo = [0.3, 0.3, 0.3]
pos_x = 0.0
pos_y = 0.0
pos_z = 20.0
width = 40.0
height = 8.0
depth = 0.2

# east wall (glass bottom)
[[box]]
material = "glass"
rough = 0.005
albedo = [0.7, 0.7, 0.7]
pos_x = 40
pos_y = 0.0
pos_z = 0.0
width = 1
height = 4.5
depth = 20

# Door in glass wall
[[box.hole]]
pos_x = 40
pos_y = 0
pos_z = 8
width = 4
height = 4.0
depth = 5

# east wall (top cover)
[[box]]
material = "diffuse"
reflect = 0.3
rough = 0.005
albedo = [0.01, 0.01, 0.01]
pos_x = 40
pos_y = 4.5
pos_z = 0.0
width = 1
height = 4.5
depth = 20.0

# Art deco door frame
[[include]]
file = "objects/art-deco-door-frame.toml"
transform_origin = [0, 0, 0]
at = [40, 0, 8]
props = { width = 5, height = 4, depth = 1, texture = "marble", albedo = [0.7, 0.7, 0.7], reflect = 0.02}

[[include]]
transform_origin = [0,0,0]
at = [31, 0.2, 18]
file = "../objects/office-table.toml"

[[include]]
transform_origin = [0,0,0]
rotate_y = 170
file = "objects/workstation-monitor.toml"
props = { case_albedo = [0.1, 0.1, 0.1], headline = "reality clstr 0.3.11", paragraphs = [
  "---------- load ----------",
  "      server 0 ... 23.9%",
  "      server 1  ... 81.3%",
  "      server 2 ... 31.2%",
  "      server 3 ... 78.1%",
  "      server 4 ... 80.0%",
  "      server 5 ... 81.3%",
  "      server 6 ... 31.2%",
  "      server 7 ... 78.1%",
]}
at = [31, 1, 18]

[[include]]
transform_origin = [0,0,0]
rotate_y = 170
file = "objects/workstation-keyboard.toml"
props = { case_albedo = [0.1, 0.1, 0.1]}
at = [31, 1.1, 18]

[[include]]
file = "../objects/office-chair.toml"
transform_origin = [0,0,0]
rotate_y = 205
at = [30.5, 0.2, 16.7]

# left column (door side)
[[cylinder]]
reflect = 0.02
rough = 0.005
material = "diffuse"
texture = "marble"
albedo = [0.2, 0.2, 0.2]
pos_x = 38
pos_y = 0
pos_z = 3
width = 1
height = 8.0
depth = 1.0

# right column (door side)
[[cylinder]]
reflect = 0.02
rough = 0.005
material = "diffuse"
texture = "marble"
albedo = [0.2, 0.2, 0.2]
pos_x = 38
pos_y = 0
pos_z = 17
width = 1
height = 8.0
depth = 1.0

# right column (cube side)
[[cylinder]]
reflect = 0.02
rough = 0.005
material = "diffuse"
texture = "marble"
albedo = [0.2, 0.2, 0.2]
pos_x = 3
pos_y = 0
pos_z = 3
width = 1
height = 8.0
depth = 1.0

# left column (cube side)
[[cylinder]]
reflect = 0.02
rough = 0.005
material = "diffuse"
texture = "marble"
albedo = [0.2, 0.2, 0.2]
pos_x = 3
pos_y = 0
pos_z = 17
width = 1
height = 8.0
depth = 1.0

# cube
[[include]]
file = "../objects/cube.toml"
# migrated-center-at
at = [11.75, 4.0, 3.5]
rotate_y = 0.0

# server rack left of the cube
[[include]]
file = "objects/server-column.toml"
# migrated-center-at
at = [4.925, 1.5, 7.235]
rotate_y = 30
instance = true

# server rack opposite the cube
[[include]]
file = "objects/server-column.toml"
# migrated-center-at
at = [8.625, 1.5, 15.285]
rotate_y = -30
instance = true

# server racks right of the cube
[[include]]
file = "objects/server-column.toml"
# migrated-center-at
at = [20.3, 1.5, 5.95]
rotate_y = 90
instance = true

[[include]]
file = "objects/server-column.toml"
# migrated-center-at
at = [23.3, 1.5, 5.95]
rotate_y = 90
instance = true

[[include]]
file = "objects/server-column.toml"
# migrated-center-at
at = [26.3, 1.5, 5.95]
rotate_y = 90
instance = true

[[include]]
file = "objects/server-column.toml"
# migrated-center-at
at = [29.3, 1.5, 5.95]
rotate_y = 90
instance = true

# server racks on the other side of the room
[[include]]
file = "objects/server-column.toml"
# migrated-center-at
at = [20.3, 1.5, 15.95]
rotate_y = 90
instance = true

[[include]]
file = "objects/server-column.toml"
# migrated-center-at
at = [23.3, 1.5, 15.95]
rotate_y = 90
instance = true

[[include]]
file = "objects/server-column.toml"
# migrated-center-at
at = [26.3, 1.5, 15.95]
rotate_y = 90
instance = true

[[include]]
file = "objects/server-column.toml"
# migrated-center-at
at = [29.3, 1.5, 15.95]
rotate_y = 90
instance = true


# stairs to the cube
[[include]]
file = "../objects/staircase.toml"
transform_origin = [0, 0, 0]
at = [9.7, 0, 7.5]
rotate_y = 90
props = { steps = 6, run = 0.3, rise = 0.2, width = 4, texture = "marble", reflect = 0.07, rough = 0.01 }

# Lamp 1 (in the middle of the room)
[[include]]
instance = true
file = "../objects/otto-wagner-sphere-lamp.toml"
# migrated-center-at
at = [25.0, 6.52, 16.0]
props = { stem_len = 2.3, brightness = 0.05, range = 10, orb_radius = 0.5 }

# Lamp 2 (middle of the room)
[[include]]
instance = true
file = "../objects/otto-wagner-sphere-lamp.toml"
# migrated-center-at
at = [25.0, 6.52, 3.5]
props = { stem_len = 2.3, brightness = 0.05, range = 20, orb_radius = 0.5 }

# Lamp 3 (very dim) above the desk
[[include]]
instance = true
file = "../objects/art-deco-ring-lamp.toml"
at = [8.0, 6.17, 9.0]
props = { stem_len = 4, brightness = 0.1, range = 10 }

# Lamp 4 (above the door)
[[include]]
instance = true
file = "../objects/art-deco-ring-lamp.toml"
# migrated-center-at
at = [35.0, 6.52, 10.5]
props = { stem_len = 3, brightness = 0.2, range = 20, top_radius = 1.5, bottom_radius = 0.5, rings = 7 }


# desk to the left of the cube
[[include]]
file = "objects/server-room-desk.toml"
# migrated-center-at
at = [8.0, 0.845, 9.498]

# switch cupboard opposite the cube
[[include]]
file = "../objects/cupboard-double-door.toml"
at = [15.0, 1.5, 19]
props = { width = 2, height = 3.0, depth = 0.5, shelves = 4, albedo = [0.5, 0.5, 0.7 ], reflect = 0.1, rough = 0.01, handle_radius = 0.1 }

# table to the right of the cube
[[include]]
file = "../objects/simple-table.toml"
# migrated-center-at
at = [14.7, 0.65, 7.0]
rotate_y = -20
props = { width = 1.5, height = 0.9, texture = "wood" }
# glass bottle on the table
[[include]]
instance = true
file = "../objects/glass-bottle.toml"
# migrated-center-at
at = [14.05, 1.25, 7.35]
# ashtray on the table
[[include]] 
instance = true
file = "../objects/ashtray.toml"
# migrated-center-at
at = [14.478, 1.119, 7.417]
rotate_y = -50


#npc walking around
# [[npc]]
# rig = "data/rigs/humanoid.yaml"
# pose = "idle"
# at = [8.0, 0.2, 10.0]
# speed = 1
# patrol = [[8, 0.2, 12.0], [16, 0.2, 18.0], [8.0, 0.2, 18.0]]

