#!/bin/sh
# Link pt.wesl (the experimental path tracer) against the megakernel's shared
# WESL modules into a single WGSL file.
#
# The shared modules are *copied* into a scratch directory rather than pt.wesl
# being dropped into modules/: shaders.ModulesSHA256 hashes every file in
# modules/, so adding one there would invalidate the megakernel's
# trace_linked.wgsl stamp and force it to relink. This experiment does not touch
# the shipping renderer's state.
set -e
cd "$(dirname "$0")"

shared="../modules"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

mkdir -p "$work/modules"
cp "$shared"/*.wesl "$work/modules/"
cp pt.wesl "$work/modules/"
cat >"$work/wesl.toml" <<'TOML'
edition = "2026_pre"
root = "./modules/pt.wesl"
include = ["./modules/**/*.wesl"]
TOML

out="pt_linked.wgsl"
tmp="$work/out.wgsl"
if command -v wesl >/dev/null 2>&1; then
	(cd "$work" && wesl compile modules/pt.wesl) >"$tmp"
else
	(cd "$work" && npx --yes wesl-link pt --baseDir modules --src '**/*.w[eg]sl') >"$tmp"
fi

python3 -c '
import re, sys
text = sys.stdin.read().lstrip("\n")
text = re.sub(r"\n{3,}", "\n\n", text)
if text and not text.endswith("\n"):
    text += "\n"
sys.stdout.write(text)
' <"$tmp" >"$tmp.norm"

hash=$(for f in "$shared"/*.wesl pt.wesl; do printf '%s\n' "$(basename "$f")"; cat "$f"; done | shasum -a 256 | cut -d' ' -f1)
{
	printf '// Code generated by pt/link.sh from ../modules/*.wesl + pt.wesl. DO NOT EDIT.\n'
	printf '// pt-modules-sha256: %s\n' "$hash"
	cat "$tmp.norm"
} >"$out"

echo "wrote $out ($(wc -l <"$out" | tr -d ' ') lines)"
