#!/bin/sh
# Link WESL shader modules into a single WGSL file for WebGPU.
# Requires Node (npx wesl-link) or Rust wesl-cli (cargo install wesl-cli).
set -e
cd "$(dirname "$0")"

python3 gen_imports.py

out="trace_linked.wgsl"
tmp="$out.tmp"
if command -v wesl >/dev/null 2>&1; then
	# https://github.com/webgpu-tools/wesl-rs — wesl compile links imports to flat WGSL
	wesl compile modules/trace.wesl >"$tmp"
else
	npx --yes wesl-link trace --baseDir modules --src '**/*.w[eg]sl' >"$tmp"
fi

# Drop leading blank lines and collapse runs of empty lines from linker output.
python3 -c '
import re, sys
text = sys.stdin.read().lstrip("\n")
text = re.sub(r"\n{3,}", "\n\n", text)
if text and not text.endswith("\n"):
    text += "\n"
sys.stdout.write(text)
' <"$tmp" >"${tmp}.norm"
mv "${tmp}.norm" "$tmp"

# Stamp the output with a digest of the module sources (post gen_imports.py)
# so TestLinkedWGSLMatchesModules can flag a stale trace_linked.wgsl.
# Must mirror the hash computed in link_test.go.
hash=$(for f in modules/*.wesl; do printf '%s\n' "$f"; cat "$f"; done | shasum -a 256 | cut -d' ' -f1)
{
	printf '// Code generated by link.sh from modules/*.wesl. DO NOT EDIT.\n'
	printf '// modules-sha256: %s\n' "$hash"
	cat "$tmp"
} >"$out"
rm "$tmp"

echo "wrote $out ($(wc -l <"$out" | tr -d ' ') lines)"
